<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>
            Dnspod API
            </title>
            <meta name="viewport" content="width=device-width,initial-scale=1.0">
            <link href="http://libs.baidu.com/bootstrap/2.0.4/css/bootstrap.min.css" rel="stylesheet" media="screen">
            </head>
            <body>
            
               <div class="span12 well pricehover">
     		   		<div class="navbar">
    				<div class="navbar-inner">
      				<div class="container">
        				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          				<span class="icon-bar"></span>
          				<span class="icon-bar"></span>
          				<span class="icon-bar"></span>
        				</a>
        			<a class="brand" href="/DNSPod/public/Index/">DNSPod</a>
        			<div class="nav-collapse">
          				<ul class="nav nav-pills">
            				<li class="active"><a href="/DNSPod/public/Index/">Home</a></li>
            				<li><a href="#">D监控</a></li>
            				<li><a href="#">购买套餐</a></li>
            				<li><a href="#">About</a></li>
          				</ul>
          			<form class="navbar-search pull-left" action="">
            			<input type="text" class="search-query span2" placeholder="Search">
          			</form>
                	</div>
                	</div>
                	</div>
               		</div>
                
                <br />
                <div class="container-fluid">
                   <div class="alert alert-danger"><?=($err_msg)?></div>
                </div>
</div>
                <script src="http://code.jquery.com/jquery.js"></script>
                <script src="http://libs.baidu.com/bootstrap/2.0.4/js/bootstrap.min.js"></script>
               
            </body>
</html>
