<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>
            Dnspod API
            </title>
            <meta name="viewport" content="width=device-width,initial-scale=1.0">
            <link href="../public/css/bootstrap.min.css" rel="stylesheet" media="screen">
            </head>
            <body>
            
               <div class="span12 well pricehover">
     		   		<div class="navbar">
    				<div class="navbar-inner">
      				<div class="container">
        				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          				<span class="icon-bar"></span>
          				<span class="icon-bar"></span>
          				<span class="icon-bar"></span>
        				</a>
        			<a class="brand" href="#">DNSPod</a>
        			<div class="nav-collapse">
          				<ul class="nav nav-pills">
            				<li class="active"><a href="#">Home</a></li>
            				<li><a href="#">D监控</a></li>
            				<li><a href="#">购买套餐</a></li>
            				<li><a href="#">About</a></li>
          				</ul>
          			<form class="navbar-search pull-left" action="">
            			<input type="text" class="search-query span2" placeholder="Search">
          			</form>
                	</div>
                	</div>
                	</div>
               		</div>
                
                <br />
                <div class="container-fluid">
                  <div class="row-fluid">
                      <div class="span3"></div>
                          <div class="span3">
                           <a href=""><input type="button" class="btn btn-success" value="添加域名"></a>
                            <div class="btn-group">
                                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                                   	 更多
                                  	<span class="caret"></span>
                                 </a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">删除</a></li>
                                    <li><a href="#">停用</a></li>
                                </ul>
                            </div>
                          </div>
                          <div class="span6"></div>
                    <div class="span2">
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="">全部域名</a></li>
                            <li><a href="">最新域名</a></li>
                            <li><a href="">错误域名</a></li>
                        </ul>
                      <!--Sidebar content-->
                    </div>
                    <div class="span9" style="display:none">
                      <table class="table table-condensed">
                        <tr><td>
                      <input type="text" name="domain_name">
                    </td>
                    <td><a href="/DNSPod/public/Domain/add"><input type="button" name="add_domain"></a></td>
                    </tr>
                      </table>
                    </div>
                    <div class="span9">
                      <!--Body content-->
                      <table class="table table-condensed" >

                          <tr><td><input type="checkbox"></td>
                          	  <td>域名</td>
                          	  <td>操作</td></tr>
                          <?
                          //var_dump($config);
                          foreach($domain_list['domains'] as $key=>$item){ ?>
                          
                          <tr>
                          	  <td><input type="checkbox"></td>
                          	  <td><a href="#" ><?=$item?></a></td>
                          	  <td><a href="#"><?echo "修改"?></a></td>
                          	
                          </tr>
                          <? } ?>
                         
                      </table>
                    </div>
                  </div>
                </div>
</div>
                <script src="http://code.jquery.com/jquery.js"></script>
                <script src="../public/js/bootstrap.min.js"></script>
            </body>
</html>
